import { type ListableResourceType } from '@commercelayer/sdk/lib/cjs/api'

const singularLowercase: Record<ListableResourceType, string> = {
  addresses: 'address',
  adjustments: 'adjustment',
  adyen_gateways: 'Adyen gateway',
  adyen_payments: 'Adyen payment',
  attachments: 'attachment',
  authorizations: 'authorization',
  avalara_accounts: 'Avalara account',
  axerve_gateways: 'Axerve gateway',
  axerve_payments: 'Axerve payment',
  billing_info_validation_rules: 'billing info validation rule',
  bing_geocoders: 'Bing geocoder',
  braintree_gateways: 'Braintree gateway',
  braintree_payments: 'Braintree payment',
  bundles: 'bundle',
  captures: 'capture',
  carrier_accounts: 'carrier account',
  checkout_com_gateways: 'Checkout.com gateway',
  checkout_com_payments: 'Checkout.com payment',
  cleanups: 'cleanup',
  coupon_codes_promotion_rules: 'coupon codes promotion rule',
  coupon_recipients: 'coupon recipient',
  coupons: 'coupon',
  customer_addresses: 'customer address',
  customer_groups: 'customer group',
  customer_password_resets: 'customer password reset',
  customer_payment_sources: 'customer payment source',
  customer_subscriptions: 'customer subscription',
  customers: 'customer',
  delivery_lead_times: 'delivery lead time',
  event_callbacks: 'event callback',
  events: 'event',
  exports: 'export',
  external_gateways: 'external gateway',
  external_payments: 'external payment',
  external_promotions: 'external promotion',
  external_tax_calculators: 'external tax calculator',
  fixed_amount_promotions: 'fixed amount promotion',
  fixed_price_promotions: 'fixed price promotion',
  free_gift_promotions: 'free gift promotion',
  free_shipping_promotions: 'free shipping promotion',
  geocoders: 'geocoder',
  gift_card_recipients: 'gift card recipient',
  gift_cards: 'gift card',
  google_geocoders: 'Google geocoder',
  imports: 'import',
  in_stock_subscriptions: 'in stock subscription',
  inventory_models: 'inventory model',
  inventory_return_locations: 'inventory return location',
  inventory_stock_locations: 'inventory stock location',
  klarna_gateways: 'Klarna gateway',
  klarna_payments: 'Klarna payment',
  line_item_options: 'line item option',
  line_items: 'line item',
  manual_gateways: 'manual gateway',
  manual_tax_calculators: 'manual tax calculator',
  markets: 'market',
  merchants: 'merchant',
  order_amount_promotion_rules: 'order amount promotion rule',
  order_copies: 'order copy',
  order_factories: 'order factory',
  order_subscription_items: 'order subscription item',
  order_subscriptions: 'order subscription',
  order_validation_rules: 'order validation rule',
  orders: 'order',
  packages: 'package',
  parcel_line_items: 'parcel line item',
  parcels: 'parcel',
  payment_gateways: 'payment gateway',
  payment_methods: 'payment method',
  paypal_gateways: 'PayPal gateway',
  paypal_payments: 'PayPal payment',
  percentage_discount_promotions: 'percentage discount promotion',
  price_frequency_tiers: 'price frequency tier',
  price_lists: 'price list',
  price_tiers: 'price tier',
  price_volume_tiers: 'price volume tier',
  prices: 'price',
  promotion_rules: 'promotion rule',
  promotions: 'promotion',
  recurring_order_copies: 'recurring order copy',
  refunds: 'refund',
  return_line_items: 'return line item',
  returns: 'return',
  satispay_gateways: 'Satispay gateway',
  satispay_payments: 'Satispay payment',
  shipments: 'shipment',
  shipping_categories: 'shipping category',
  shipping_method_tiers: 'shipping method tier',
  shipping_methods: 'shipping method',
  shipping_weight_tiers: 'shipping weight tier',
  shipping_zones: 'shipping zone',
  sku_list_items: 'SKU list item',
  sku_list_promotion_rules: 'SKU list promotion rule',
  sku_lists: 'SKU list',
  sku_options: 'SKU option',
  skus: 'SKU',
  stock_items: 'stock item',
  stock_line_items: 'stock line item',
  stock_locations: 'stock location',
  stock_transfers: 'stock transfer',
  stripe_gateways: 'Stripe gateway',
  stripe_payments: 'Stripe payment',
  subscription_models: 'subscription model',
  tax_calculators: 'tax calculator',
  tax_categories: 'tax category',
  tax_rules: 'tax rule',
  taxjar_accounts: 'TaxJar account',
  transactions: 'transaction',
  voids: 'void',
  webhooks: 'webhook',
  wire_transfers: 'wire transfer'
}

const pluralLowercase: Record<ListableResourceType, string> = {
  addresses: 'addresses',
  adjustments: 'adjustments',
  adyen_gateways: 'Adyen gateways',
  adyen_payments: 'Adyen payments',
  attachments: 'attachments',
  authorizations: 'authorizations',
  avalara_accounts: 'Avalara accounts',
  axerve_gateways: 'Axerve gateways',
  axerve_payments: 'Axerve payments',
  billing_info_validation_rules: 'billing info validation rules',
  bing_geocoders: 'Bing geocoders',
  braintree_gateways: 'Braintree gateways',
  braintree_payments: 'Braintree payments',
  bundles: 'bundles',
  captures: 'captures',
  carrier_accounts: 'carrier accounts',
  checkout_com_gateways: 'Checkout.com gateways',
  checkout_com_payments: 'Checkout.com payments',
  cleanups: 'cleanups',
  coupon_codes_promotion_rules: 'coupon codes promotion rules',
  coupon_recipients: 'coupon recipients',
  coupons: 'coupons',
  customer_addresses: 'customer addresses',
  customer_groups: 'customer groups',
  customer_password_resets: 'customer password resets',
  customer_payment_sources: 'customer payment sources',
  customer_subscriptions: 'customer subscriptions',
  customers: 'customers',
  delivery_lead_times: 'delivery lead times',
  event_callbacks: 'event callbacks',
  events: 'events',
  exports: 'exports',
  external_gateways: 'external gateways',
  external_payments: 'external payments',
  external_promotions: 'external promotions',
  external_tax_calculators: 'external tax calculators',
  fixed_amount_promotions: 'fixed amount promotions',
  fixed_price_promotions: 'fixed price promotions',
  free_gift_promotions: 'free gift promotions',
  free_shipping_promotions: 'free shipping promotions',
  geocoders: 'geocoders',
  gift_card_recipients: 'gift card recipients',
  gift_cards: 'gift cards',
  google_geocoders: 'Google geocoders',
  imports: 'imports',
  in_stock_subscriptions: 'in stock subscriptions',
  inventory_models: 'inventory models',
  inventory_return_locations: 'inventory return locations',
  inventory_stock_locations: 'inventory stock locations',
  klarna_gateways: 'Klarna gateways',
  klarna_payments: 'Klarna payments',
  line_item_options: 'line item options',
  line_items: 'line items',
  manual_gateways: 'manual gateways',
  manual_tax_calculators: 'manual tax calculators',
  markets: 'markets',
  merchants: 'merchants',
  order_amount_promotion_rules: 'order amount promotion rules',
  order_copies: 'order copies',
  order_factories: 'order factories',
  order_subscription_items: 'order subscription items',
  order_subscriptions: 'order subscriptions',
  order_validation_rules: 'order validation rules',
  orders: 'orders',
  packages: 'packages',
  parcel_line_items: 'parcel line items',
  parcels: 'parcels',
  payment_gateways: 'payment gateways',
  payment_methods: 'payment methods',
  paypal_gateways: 'PayPal gateways',
  paypal_payments: 'PayPal payments',
  percentage_discount_promotions: 'percentage discount promotions',
  price_frequency_tiers: 'price frequency tiers',
  price_lists: 'price lists',
  price_tiers: 'price tiers',
  price_volume_tiers: 'price volume tiers',
  prices: 'prices',
  promotion_rules: 'promotion rules',
  promotions: 'promotions',
  recurring_order_copies: 'recurring order copies',
  refunds: 'refunds',
  return_line_items: 'return line items',
  returns: 'returns',
  satispay_gateways: 'Satispay gateways',
  satispay_payments: 'Satispay payments',
  shipments: 'shipments',
  shipping_categories: 'shipping categories',
  shipping_method_tiers: 'shipping method tiers',
  shipping_methods: 'shipping methods',
  shipping_weight_tiers: 'shipping weight tiers',
  shipping_zones: 'shipping zones',
  sku_list_items: 'SKU list items',
  sku_list_promotion_rules: 'SKU list promotion rules',
  sku_lists: 'SKU lists',
  sku_options: 'SKU options',
  skus: 'SKUs',
  stock_items: 'stock items',
  stock_line_items: 'stock line items',
  stock_locations: 'stock locations',
  stock_transfers: 'stock transfers',
  stripe_gateways: 'Stripe gateways',
  stripe_payments: 'Stripe payments',
  subscription_models: 'subscription models',
  tax_calculators: 'tax calculators',
  tax_categories: 'tax categories',
  tax_rules: 'tax rules',
  taxjar_accounts: 'TaxJar accounts',
  transactions: 'transactions',
  voids: 'voids',
  webhooks: 'webhooks',
  wire_transfers: 'wire transfers'
}

/**
 * Format a resource name for display in the UI based on the count and format.
 * default format is lower case and singular
 */
export function formatResourceName({
  resource,
  count = 1,
  format = 'lower'
}: {
  resource: ListableResourceType
  count?: number | 'singular' | 'plural'
  format?: 'lower' | 'title'
}): string {
  const isSingular = count === 1 || count === 'singular'
  const dictionary = isSingular ? singularLowercase : pluralLowercase
  const resourceName = dictionary[resource]

  if (resourceName == null) {
    return resource
  }

  if (format === 'title') {
    return capitalizeFirstLetter(resourceName)
  }

  return resourceName
}

function capitalizeFirstLetter(string: string): string {
  return string.charAt(0).toUpperCase() + string.slice(1)
}
