packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
allowBuilds:
  esbuild: true
  msw: true
  nx: true
minimumReleaseAgeExclude:
  - '@commercelayer/sdk'
  - '@tanstack/react-table'
  - '@tanstack/table-core@9.0.0'
