export const presets = {
  gift_card:
    "https://data.commercelayer.app/assets/images/icons/items/gift-card.svg",
  "carriers:generic":
    "https://data.commercelayer.app/assets/images/icons/carriers/generic.svg",
  "carriers:fedex":
    "https://data.commercelayer.app/assets/images/icons/carriers/fedex.svg",
  "carriers:ups":
    "https://data.commercelayer.app/assets/images/icons/carriers/ups.svg",
  "carriers:dhl":
    "https://data.commercelayer.app/assets/images/icons/carriers/dhl.svg",
  "payments:stripe":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/stripe.svg",
  "payments:braintree":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/braintree.svg",
  "payments:paypal":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/paypal.svg",
  "payments:klarna":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/klarna.svg",
  "payments:checkout":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/checkout.svg",
  "payments:adyen":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/adyen.svg",
  "payments:axerve":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/axerve.svg",
  "payments:satispay":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/satispay.svg",
  "payments:manual":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/manual-service.svg",
  "payments:external":
    "https://data.commercelayer.app/assets/images/icons/payment-gateways/external-service.svg",
  "tax-calculators:avalara":
    "https://data.commercelayer.app/assets/images/icons/tax-calculators/avalara.svg",
  "tax-calculators:taxjar":
    "https://data.commercelayer.app/assets/images/icons/tax-calculators/taxjar.svg",
  "tax-calculators:manual":
    "https://data.commercelayer.app/assets/images/icons/tax-calculators/manual-service.svg",
  "tax-calculators:external":
    "https://data.commercelayer.app/assets/images/icons/tax-calculators/external-service.svg",
}
