import type { Address } from "@commercelayer/sdk"

export const presetAddresses = {
  withName: {
    type: "addresses",
    id: "aaZYuDJVXW",
    business: false,
    company: "",
    first_name: "Darth",
    last_name: "Vader",
    full_name: "Darth Vader",
    line_1: "Via Morte Nera, 13",
    line_2: "Ragnatela, 99",
    city: "Cogorno",
    country_code: "IT",
    state_code: "GE",
    zip_code: "16030",
    phone: "+39 055 1234567890",
    billing_info: "ABCDEFGHIJKLMNOPQRSTUVWYXZ",
    created_at: "",
    updated_at: "",
  },
  withCompany: {
    type: "addresses",
    id: "bbZYuDJVXW",
    business: true,
    company: "Galactic Empire",
    first_name: "",
    last_name: "",
    full_name: "Galactic Empire",
    line_1: "Via Morte Nera, 13",
    line_2: "Ragnatela, 99",
    city: "Cogorno",
    country_code: "IT",
    state_code: "GE",
    zip_code: "16030",
    phone: "+39 055 1234567890",
    billing_info: "ABCDEFGHIJKLMNOPQRSTUVWYXZ",
    created_at: "",
    updated_at: "",
  },
  withNotes: {
    type: "addresses",
    id: "ccZYuDJVXW",
    company: "Rebellion",
    first_name: "Luke",
    last_name: "Skywalker",
    full_name: "Luke Skywalker",
    line_1: "Via Polis Massa, 42",
    line_2: "Ragnatela, 99",
    city: "Cogorno",
    country_code: "IT",
    state_code: "GE",
    zip_code: "16030",
    phone: "+39 055 1234567890",
    billing_info: "ABCDEFGHIJKLMNOPQRSTUVWYXZ",
    created_at: "",
    updated_at: "",
    notes: "Kindly leave the package to my neighbor, Adam Sandler.",
  },
  withErrors: {
    type: "addresses",
    id: "ddZYuDJVXW",
    company: "",
    first_name: "",
    last_name: "",
    full_name: "",
    line_1: "Via Polis Massa, 42",
    line_2: "Ragnatela, 99",
    city: "Cogorno",
    country_code: "IT",
    state_code: "GE",
    zip_code: "16030",
    phone: "+39 055 1234567890",
    billing_info: "ABCDEFGHIJKLMNOPQRSTUVWYXZ",
    created_at: "",
    updated_at: "",
    notes: "Kindly leave the package to my neighbor, Adam Sandler.",
  },
} satisfies Record<string, Address>
