import * as phosphor from '@phosphor-icons/react'

export const iconMapping = {
  arrowBendDownRight: phosphor.ArrowBendDownRight,
  apps: phosphor.SquaresFour,
  arrowCircleDown: phosphor.ArrowCircleDown,
  arrowClockwise: phosphor.ArrowClockwise,
  arrowDown: phosphor.ArrowDown,
  arrowLeft: phosphor.ArrowLeft,
  arrowsLeftRight: phosphor.ArrowsLeftRight,
  arrowUpRight: phosphor.ArrowUpRight,
  asterisk: phosphor.AsteriskSimple,
  caretRight: phosphor.CaretRight,
  chatCircle: phosphor.ChatCircle,
  check: phosphor.Check,
  cloud: phosphor.CloudArrowUp,
  credentials: phosphor.LockSimpleOpen,
  creditCard: phosphor.CreditCard,
  download: phosphor.Download,
  eye: phosphor.Eye,
  flag: phosphor.Flag,
  funnel: phosphor.FunnelSimple,
  github: phosphor.GithubLogo,
  google: phosphor.GoogleLogo,
  home: phosphor.HouseSimple,
  hourglass: phosphor.Hourglass,
  magnifyingGlass: phosphor.MagnifyingGlass,
  minus: phosphor.Minus,
  package: phosphor.Package,
  pencilSimple: phosphor.PencilSimple,
  printer: phosphor.Printer,
  pulse: phosphor.Pulse,
  resources: phosphor.Stack,
  settings: phosphor.GearFine,
  shoppingBag: phosphor.ShoppingBag,
  team: phosphor.Users,
  truck: phosphor.Truck,
  upload: phosphor.Upload,
  user: phosphor.User,
  warning: phosphor.Warning,
  warningCircle: phosphor.WarningCircle,
  x: phosphor.X
} as const
