name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node: [22.22.2, 22.x, 24.x, 26.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: pnpm 🧰
        uses: pnpm/action-setup@v5

      - name: Node 🧰
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install

      - name: Run Check 💅
        run: pnpm check

      - name: Run TS check 🔎
        run: pnpm ts:check

      - name: Run Audit 🔬
        run: pnpm audit || exit 0

      - name: Run Unit Tests 🧪
        run: pnpm test
